### ISSUE TITLE
Alexa Voice Service

### ISSUE THREAD

**Issue by manask88** [willblaschko/AlexaAndroid#1]
Awesome example, thanks very much for this!. Amazon documentation is really tough to digest, so this is super helpful.
I was wondering if you have considered using Alexa Voice Service? Is there any reason to use Google Speach Recognition engine instead of Alexa's?

**Comment by willblaschko** [comment]
First off, I'm glad my efforts muddling through the process have helped!

This is one of the inefficiencies of the sample app, and something I wanted to leave as an option to developers using this library. I did this, also, for the simplicity of the demo app: no record audio permissions for Android-L, no end of speech recognition.

What is happening is the spoken command is being parsed by Google, translated into written text, made into an audio file (text-to-speech) and then parsed again by Alexa Voice Service. You can see the obvious inefficiencies with this process.

Ideally a developer would use the following two commands and either trigger stopRecording by a end of speech trigger (however one wanted to measure that--there is one built into the OS with [SpeechRecognizer](http://developer.android.com/reference/android/speech/SpeechRecognizer.html)) or a button press:

```
//Start creating a request using audio but prepend a byte array
//(raw audio recorded at the correct bitrate) to the front of the request: "Open MySkillKit and..."
mAlexaManager.startRecording(REQUEST_TYPE.TYPE_VOICE_RESPONSE, byte[]..., AsyncCallback...);

//Stop recording the request and send it to the Alexa server,
//process results on the AsyncCallback
mAlexaManager.stopRecording(AsynCallback...);
```

What the startRecording() and stopRecording() methods do is create an audio file that is uploaded directly, versus counting on Google to transcribe. This will give you the most responsive voice transaction and, likely, the most accurate one as well.

The time difference between these two ways of recording audio--that is, start + stop versus using the built in Android intent--on a Moto X 2014 was < 1000ms (usually around 800), so noticeable, but not overly so.

Does this answer your question?

**Comment by manask88** [comment]
yes! @willblaschko  Because of your explanation now I think I understand better what Alexa Voice Service is really able to do. Thanks!

**Comment by willblaschko** [comment]
Great!
