### ISSUE TITLE
How to convert STT and TTS in the app

### ISSUE THREAD

**Issue by venkateshsubbiah** [willblaschko/AlexaAndroid#101]
I'm getting AvsReponse as result and giving RawAudioRecorder as input. I wish to extract text equivalent from AvsResponse object and text out of RawAudioRecorder. Thanks in advance

**Comment by venkateshsubbiah** [comment]
Is it not a problem for most. ??

**Comment by amiga** [comment]
Its a problem for me too I cannot work out how to get the text value of what I said, or what Alexa said.

**Comment by venkateshsubbiah** [comment]
Is it possible to use display cards for getting the text of the response? Reference: [https://developer.amazon.com/blogs/alexa/post/fb935c08-0985-4507-8219-6a2a607e2e36/display-cards-for-alexa-bring-visual-experiences-to-avs-products](url)

**Comment by willblaschko** [comment]
As long as you're making sure to not expose data to an external service, you could use a library on device to transcribe both what is sent and what is returned.
