### ISSUE TITLE
Unable to play from tunein

### ISSUE THREAD

**Issue by Nishad009** [willblaschko/AlexaAndroid#109]
Is it possible to add tunein support using Alexa Voice Library?
Right now whan I say "tune in to <station name>",  always getting "tunein not supported in your device" message.

**Comment by KushtrimPacaj** [comment]
For music services you should contact Amazon. You will have to certify your device first before gaining access to the music services.

**Comment by willblaschko** [comment]
I've talked to them, unfortunately due to licensing issues, non-hardware solutions aren't generally supported. If you're embedding Android in a hardware player, it's possible you'll be able to stream music services.
