### ISSUE TITLE
Error trying to run one of the demos.

### ISSUE THREAD

**Issue by nospam2k** [willblaschko/AlexaAndroid#110]
When I try to run one of the demos (fresh compile of AlexaAndroid with only a few touch ups for later sdk 26), I get the LoginWithAmazon browser. After loging in and clicking "I agree" I get this error:

We're sorry
An error occurred when we tried to process your request. Rest assured, we're already working on the problem and expect to resolve it shortly.

Is this really true? Other Alexa apps that I use seem to login ok. Thanks.

The only error in the logcat is:

.android.alexavoicelibrary I/com.amazon.identity.auth.device.utils.ThirdPartyResourceParser: Attempting to parse API Key from assets directory
08-22 20:20:28.170 9494-9494/com.willblaschko.android.alexavoicelibrary W/System.err: Caused by: java.lang.IllegalStateException: User is not logged in and no refresh token found.
08-22 20:20:28.170 9494-9494/com.willblaschko

There is no problem (it seems) processing the api_key.txt file as there are none of the normal errors about not being found or invalid. I don't get the Toast saying invalid api_key.txt

**Comment by KushtrimPacaj** [comment]
Because of the aforementioned error, it seems tokens were not saved, and not much you can do without them.

Is the error showing on Amazon login page? Have you tried with another Amazon account ? Have you tried installing their Android app, and login via the app?

**Comment by nospam2k** [comment]
It seems the problem was related to the Product id/security profile. I don't know why yet. I have made a previous one and that works ok. So problem is Amazon.
