### ISSUE TITLE
Logged in User details 

### ISSUE THREAD

**Issue by rohith-krish** [willblaschko/AlexaAndroid#111]
How to get the details of the user logged in ??
Like the email id and name etc.

**Comment by syedtalha** [comment]
Fetch the access token, then call this api:

https://api.amazon.com/user/profile
Header: Authorization", Bearer access_token

**Comment by rohith-krish** [comment]
Could you please provide a sample code

**Comment by syedtalha** [comment]
String url = "https://api.amazon.com/user/profile";
        OkHttpClient client = ClientUtil.getTLS12OkHttpClient();

        Request request = new Request.Builder()
                .url(url)
                .addHeader("Authorization", "Bearer " + access_token)
                .build();

        client.newCall(request).enqueue(new Callback() {
            @Override
            public void onFailure(Call call, final IOException e) {

            }

            @Override
            public void onResponse(Call call, Response response) throws IOException {
                String s = response.body().string();
                
                


            }
        });

**Comment by rohith-krish** [comment]
Thanks, @syedtalha. it worked.
