### ISSUE TITLE
Confusing Wiki - Need help with setting up project

### ISSUE THREAD

**Issue by DariuschDideban** [willblaschko/AlexaAndroid#126]
Okay so i am trying to follow your steps, but it is very confusing to me.

I added the library to my Android Project and then it says:
"Follow the process for creating a connected device detailed at the Amazon link at the top of the Readme."

Problem is that when you open this link there is no process for creating a conntected device. So I am not sure what exactly is meant.

Can somebody please give me a specific link or tell me where exactly i can find it?

Greets and thanks in advance!

**Comment by syedtalha** [comment]
Pls go to the link [here](https://developer.amazon.com/avs/home.html#/avs/products/new) to create a new AVS supported device or app. In this case it will be an app, since we assume you want to integrate this into an app rather than a hardware device

**Comment by DariuschDideban** [comment]
Thanks @syedtalha ! I got it, and this worked now.
