### ISSUE TITLE
Unable to find signing.gradle, please replace Android buildTypes > signing configs with your own configuration.

### ISSUE THREAD

**Issue by silvio1308** [willblaschko/AlexaAndroid#135]
Hi, I have this error that I can not solve, I saw another post but I did not understand very well what should I do to run the build. Can you have more detailed steps to do? thanks, I use android studio and I put alexa on raspberrypi3. Thk :)

**Comment by HiteshKhatri02** [comment]
Getting same error.

**Comment by willblaschko** [comment]
Please see this: https://github.com/willblaschko/AlexaAndroid/issues/44
