### ISSUE TITLE
Is live Audio Streaming possible in AVS?

### ISSUE THREAD

**Issue by rahuljeyaraj** [willblaschko/AlexaAndroid#14]
Hi,
I would like to stream live audio (like music) to my Alexa app. Is there any way to do it?

**Comment by willblaschko** [comment]
@rahuljeyaraj that depends on whether Amazon will allow your particular app to stream music.

If you go to your particular app here: https://developer.amazon.com/edw/home.html#/avs/list and read through the documentation you can see what's supported. Currently Amazon is not supporting much for 3rd party software.

Specific skills can stream short clips of audio, but nothing extensive (I forget if the limit is 30 seconds).
