### ISSUE TITLE
not playing the amazon music

### ISSUE THREAD

**Issue by chowdary60** [willblaschko/AlexaAndroid#145]
i am running @willblaschko  sample app successfully.i linked amazon music app to sample alexa app at
https://alexa.amazon.com/spa/index.html#settings/music-settings/service-preferences. 
when i ask alexa playing something from amzon music, alexa "amazon music is not supported on this device". i am checking this emulator.what could be the problem?
i have installed amazon music in emulator and i can able to play the music in emulator it self, what could be the problem ? the  sample app @willblaschko  will not support stream music?

**Comment by prasannakumark** [comment]
+1

**Comment by chowdary60** [comment]
To link the amazon music the device should be white listed( received in amazon developer forum)
