### ISSUE TITLE
Live streaming of voice

### ISSUE THREAD

**Issue by wicky852** [willblaschko/AlexaAndroid#15]
I have not tried your solution just curious to know does your Alexa android app supports live streaming of voice and have capability of bidirectional streaming with low latency.

**Comment by rahuljeyaraj** [comment]
Any suggestion?

**Comment by willblaschko** [comment]
@wicky852 if you look at the Send Live Audio recipe in the readme, that's an example of how to send live streaming voice, which greatly reduces the latency time.The key is the DataRequestBody which grabs data from the AudioRecorder on a background thread and posts it to the opened connection to the Alexa servers.

Alexa doesn't support bidirectional streaming per se, as the payloads being returned are often data blobs and not streamable urls (although occasionally urls are returned).

However, the prompt-to-response times on the app are within the same range as the standalone Echo device in my unscientific testing.

**Comment by wicky852** [comment]
Thank you
