### ISSUE TITLE
APIKey is incorrect or does not exist

### ISSUE THREAD

**Issue by nassib92** [willblaschko/AlexaAndroid#17]
Hello, 

I have changed the product ID after creating an application on my amazon account. I keep getting the error "APIKey is incorrect or does not exist". 

Please help. Thanks

**Comment by willblaschko** [comment]
Have you changed the package name as well (to match what's on your application on the Amazon Developer dashboard)?

**Comment by nassib92** [comment]
Thanks for the quick reply!
Yes I put the same package name as yours on the Amazon application setup. Is that the wrong thing to do?

**Comment by nassib92** [comment]
Changed it but still same error. 

Also at first when I opened the project. I kept getting this error " Error:(27, 0) Could not find property 'releaseConfig' on SigningConfig container." and then i commented out the lines "                signingConfig signingConfigs.releaseConfig"

does this have anything to do with it? If so, how can I fix it?

**Comment by willblaschko** [comment]
You'll need to make sure you're signing the app with a key you control as well, I didn't include my keystore there, so you'll need to add one, and then use that to get the security md5 hash.

**Comment by nassib92** [comment]
Yes I did that by following the amazon instructions. Is there anywhere to add it in the actual code?

**Comment by willblaschko** [comment]
No, but you'll need to make sure you're signing your app with the same key for both Debug and Release and that the key you use for those matches the key you used for the MD5 security hash.

**Comment by willblaschko** [comment]
Closing.
