### ISSUE TITLE
Alarm and Timer not working

### ISSUE THREAD

**Issue by wicky852** [willblaschko/AlexaAndroid#18]
I am not able to set alarm or timer.
If I try to set an alarm, I get this response : "Sorry there is a problem setting your alarm".
If I set a timer say for 30 sec,  I don't get any alert after 30 sec.

What might be the issue??? Please Help...
Thank You... 

PS: I am using your application outside US.

**Comment by vw2k3** [comment]
Some Alexa-enabled products like mobile application don't support timers or alarms. When I set alarm or timer, Alexa always says "Alarms are not currently supported on this device."

**Comment by wicky852** [comment]
@vw2k3, Thank you for your response.

Did you get _"Alarms are not currently supported on this device."_ response in this same application or in some different AVS client application?

Following is what happens to me:
My command : "Set alarm at 5 PM"
Alexa's responds: "Alarm is set for 5 PM, Sorry there is a problem setting your alarm" 

How can I resolve it?

**Comment by vw2k3** [comment]
Of course I use this same application.

If you wanna figure out why, you can go to Alexa APP and send ur issue to Amazon support team.
Open Alexa App > Setting > History > click the item you have issue in > select"No" under "Does Alexa do what you want?" > send more detailed feedback.

**Comment by willblaschko** [comment]
@JeremiahStephenson is doing work with timers and alarms, I've merged some of his commits in.

**Comment by JeremiahStephenson** [comment]
@willblaschko You might want to pull my changes from today. What I was working on yesterday was incomplete and breaks things. I know, I shouldn't have committed it to my master branch but I did anyway. I didn't know you were going to take notice of the work I've been doing.

**Comment by willblaschko** [comment]
@JeremiahStephenson I was mostly curious who had 10 commits off a branch, I'm really thankful for the help, honestly :).

**Comment by JeremiahStephenson** [comment]
@willblaschko Yeah, no problem. I'm glad I could help out.

**Comment by raj10071997** [comment]
I am not able to set an alarm.When I try to set an alarm, it says that alarm has been set for the given time. But immediately after that I am getting this response.
"Sorry there is a problem setting your alarm". 
Can you please tell how can I solve this problem?

Thank you...

**Comment by wantitmore** [comment]
I also have this problem, have you solve this ?thx @raj10071997
