### ISSUE TITLE
authorization  failed

### ISSUE THREAD

**Issue by joinee0208** [willblaschko/AlexaAndroid#19]
hi ! first of all, thank you for AlexaAndroid open srouce project.it really help me to understand how to use alexa. but when i do all steps your readme file writed,i still cannot run the demo app normally. i always failed on the login step.

hope you can help me,thanks very much,best regards for you!

my problem is i can not authorization successed.

![image](https://cloud.githubusercontent.com/assets/3191056/16866456/a13b7a3c-4a9e-11e6-91bb-d9d396e509f2.png)
![image](https://cloud.githubusercontent.com/assets/3191056/16866475/bdc8a724-4a9e-11e6-8531-ee5703f5fc3a.png)
![image](https://cloud.githubusercontent.com/assets/3191056/16866481/c6903ab6-4a9e-11e6-9c65-0a5a1b1f048e.png)

follows are my config information and amazon's profile as readme file writed:

![image](http://i2.piimg.com/567571/4740feb70a4c55cd.png)

![image](http://i2.piimg.com/567571/28a9adccc30334b2.png)

![image](http://i2.piimg.com/567571/8102298c2c47fd68.png)

![image](http://i2.piimg.com/567571/972396aaa2b35db5.png)

**Comment by willblaschko** [comment]
Have you found a resolution for this? Everything looks right, without diving in too far.

**Comment by willblaschko** [comment]
Closing, please let me know if this is still an issue.

**Comment by a21052** [comment]
Hi, I am now getting this error. Can you let me know how to resolve this Authentication error pressing I agree. I just used your test code and modified the PRODUCT_ID

**Comment by liutao00** [comment]
same Authentication error

**Comment by liutao00** [comment]
@joinee0208 Have you solved this problem? Please give me some suggest? Thanks!
