### ISSUE TITLE
No response when trying to send Text Request 

### ISSUE THREAD

**Issue by vw2k3** [willblaschko/AlexaAndroid#2]
Hello there,
I successfully logged in and get the Access Token. But, when trying to send Text Request, it gets stuck and has no response. Then, I found that it doesn't have callback in `SendText.java` > `voiceHelper.getSpeechFromText(...)` which means that it'll not run `completePost()` send the request to Alexa server.
Do anyone know how to solve the problem?
Any help is greatly appreciated!

**Comment by willblaschko** [comment]
There are a couple places where I forgot to add callback.complete() in SendText and SendVoice (and the base SendData). But I don't know why it's not returning (I might have just been listening for onSuccess() and not onComplete(), which you'll normally want to do). I'll push the updated code, let me know if it still doesn't work and step through it to let me know which line is being called last.

**Comment by vw2k3** [comment]
Hi willblaschko,
Thanks for reply. I try to use the updated code, and it unfortunately has the same problem. I use debug mode and found that`VoiceHelper.java`>`UtteranceProgressListener` only get `onStart(...)` result and never get other results `onDone(...)`,`onError(...)`. I think it may have some problems in `VoiceHelper.java`. The following is last 9 step of  debug mode:
1
`TextToSpeech.java` >`private final ITextToSpeechCallback.Stub mCallback = new ITextToSpeechCallback.Stub()` >`onStop()` >`UtteranceProgressListener listener = mUtteranceProgressListener;`
2
`VoiceHelper.java` > `getSpeechFromText(...)`
3
`VoiceHelper.java` > `mUtteranceProgressListener(...) > onStart(...)`
4
`VoiceHelper.java` > `getSpeechFromText(...)`
5
`SendText.java` > `sendText(...)` last line
6
`TextToSpeech.java` >`private final ITextToSpeechCallback.Stub mCallback = new ITextToSpeechCallback.Stub()` >
`onStop()` >`UtteranceProgressListener listener = mUtteranceProgressListener;`
7
`AlexaManager.java` > `doInBackground(...)` > `TokenManager.getAccessToken(...)` >　`onSuccess()` last line
8
`TokenManager.java` >　`getAccessToken(...)` last line
9
`AlexaManager.java` > `doInBackground(...)` > `return null;`
After 9, it gets stuck.
Let me know if you need more information. Hope you can help me solve the problem!

**Comment by willblaschko** [comment]
Are you successfully getting an accessToken response?

**Comment by willblaschko** [comment]
Since UtteranceProgressListener is part of the TextToSpeech package, maybe something in breaking in there? Are you seeing anything in the logs (without filters on) that might indicate a problem?

**Comment by vw2k3** [comment]
Finally, I figure out that it's not a software problem but a hardware problem! The smart phone's TTS settings (in [Setting]>[Language and input]>[Text-to-speech options]>[Preferred TTS engine]) should  be better to choose "Google Text-to-speech Engine", so the TTS engine can normally work for program. My running device is ZenFone 5 (A500KL), and maybe it works well without additional setting in other devices.
Thank you for spending some time dealing with my problem!

**Comment by willblaschko** [comment]
Not a problem, I'm glad we got it figured out :). I'm going to close this issue.
