### ISSUE TITLE
Device not compatible on Google Play

### ISSUE THREAD

**Issue by TheOrangeTester** [willblaschko/AlexaAndroid#20]
I have distributed APK for beta Testing on Google Play.  Testers reporting that they are not able to install the  App as Device not compatible.

**Comment by willblaschko** [comment]
Could you upload a screenshot of the
<img width="586" alt="screen shot 2016-07-29 at 9 38 28 am" src="https://cloud.githubusercontent.com/assets/1225745/17249974/57f26610-5570-11e6-8e3c-56893808377c.png">
 APK information that looks like this from Google Play?

**Comment by TheOrangeTester** [comment]
@willblaschko : Just need to change  
compile 'org.apache.directory.studio:org.apache.commons.io:2.4'  to 'commons-io:commons-io:2.4'
