### ISSUE TITLE
error of the latest version

### ISSUE THREAD

**Issue by suihansong** [willblaschko/AlexaAndroid#21]
hi, when i use the latest version, there is a errror when start:
![1](https://cloud.githubusercontent.com/assets/7686706/17361059/0fcd1d28-59a1-11e6-80fc-0201f89430e2.png)
and when i comment out `alexaManager.sendSynchronizeStateEvent(requestCallback);` in BaseActivity, there are more errors.

**Comment by suihansong** [comment]
any suggestions?

**Comment by willblaschko** [comment]
It looks like I'm expecting there to be a TextView when there isn't, I haven't had a chance to look more closely at the code, yet. If you can figure out what's going on, submit a pull request please, if not I'll try to get to it when I can :).

**Comment by willblaschko** [comment]
This ended up being a life cycle issue, I just pushed a fix.
