### ISSUE TITLE
no audio response from AVS

### ISSUE THREAD

**Issue by ugottreich** [willblaschko/AlexaAndroid#22]
Hi,
first - thanks a lot for your contribution!
I was able to build and deploy your project, but i wasn't able to get any audio response although i'm able to see that the audio is being sent to AVS.
are you familiar with such issue?
could it be that I missed some response in the past and it somehow went out of synchronization?

thanks in advance,
Uri.

**Comment by willblaschko** [comment]
Looks like there's an issue with the Alexa service right now, lots of devs are reporting it being broken:

https://forums.developer.amazon.com/questions/33371/204-response-1.html

**Comment by ugottreich** [comment]
thanks!
will poll on it tomorrow.

**Comment by ugottreich** [comment]
just FYI, today everything works great! it seems that the problems were with Alexa service.
another question - I'm having a hard time to play iHeartRadio (or any other streaming music for that matter). it seems that mediaplayer gives an error.
are you familiar with such issue?

Uri.
