### ISSUE TITLE
MediaPlayer

### ISSUE THREAD

**Issue by ugottreich** [willblaschko/AlexaAndroid#24]
I'm having a hard time to play iHeartRadio (or any other streaming music for that matter). it seems that mediaplayer gives an error on prepare().
are you familiar with such issue?

Uri.

**Comment by willblaschko** [comment]
Hi Uri, can you breakpoint in the ResponseParser and figure out what the response coming back is?

**Comment by ugottreich** [comment]
we understood that the issue is a format issue.
we tried to open the URL with music android stock application and got a pop up that said the format isn't supported.

**Comment by willblaschko** [comment]
Closing since it's outside the scope of this library.
