### ISSUE TITLE
Popup Dialog in each request

### ISSUE THREAD

**Issue by suihansong** [willblaschko/AlexaAndroid#26]
hi, every time i send a request to AVS and play back the response audio. After that, there will be a dialog:
![12](https://cloud.githubusercontent.com/assets/7686706/17611281/77acc370-6078-11e6-9fb3-2ed2381c1e63.png)
it should be the response of AVS to `PlaybackNearlyFinishedEvent`.
i had submitted a pull request for that, sorry to cause other error: `fix speak items not triggering finished event`.
so what is the fundamental solution?
thanks very much,best regards for you!

**Comment by skypiri** [comment]
I have a same popup-dialog. Do you have resolve it?

**Comment by willblaschko** [comment]
The example app is overly verbose, and I'm figuring out how to get things to behave correctly.

If you want to deal with this directly, making the app less verbose, remove lines 348 - 359 of BaseActivity.java, the user doesn't really need to see every error that happens on the server side.

**Comment by amitks2015** [comment]
Comment out 
 `sendPlaybackNearlyFinishedEvent(item, offsetInMilliseconds);` inside playerProgress()(BaseActivity.java)
