### ISSUE TITLE
How can I get the text result from spoken?

### ISSUE THREAD

**Issue by skypiri** [willblaschko/AlexaAndroid#28]
If I can get a text result from input audio, how can I get a text result?
I want to get a just Speech To Text result. Is it possible?

**Comment by willblaschko** [comment]
@skypiri currently this is not an option for the platform, and Amazon frowns on using 3rd party APIs to do Speech to Text (as a worry for user security). Microsoft's Cognitive Services is an option, but, again, it's not recommended.

One thing you can do, locally (to comply with Amazon's user privacy preference), but takes a bit of processing power is use PocketSphinx:
http://stackoverflow.com/questions/29008111/give-a-file-as-input-to-pocketsphinx-on-android/37640851#37640851

None of these options offer really good transcription. Amazon has implied they might offer a text response in the future, but generally they refuse to talk about project road map.
