### ISSUE TITLE
Signing Problem

### ISSUE THREAD

**Issue by xtools-at** [willblaschko/AlexaAndroid#3]
Hi Will,

I'm stuck, could you help me please?
I regsitered an AVS-App with Amazon and extracted the MD5 of the certificate of the release-build APK of your sample app (using own test-keystore) with keytool like described in the Amzn documentation (can't find the link right now), but the app crashes because the fingerprint doesn't seem to match :(
```
I/com.amazon.identity.auth.device.appid.APIKeyDecoder: Begin decoding API Key for packageName=com.willblaschko.android.alexavoicelibrary
I/com.amazon.identity.auth.device.appid.APIKeyDecoder: getKeyParts for packageName=com.willblaschko.android.alexavoicelibrary
D/com.amazon.identity.auth.device.appid.APIKeyDecoder.PII: APIKey:<obscured>
I/com.amazon.identity.auth.device.appid.APIKeyDecoder: verifySignature for packageName=com.willblaschko.android.alexavoicelibrary
I/com.amazon.identity.auth.device.appid.APIKeyDecoder: verifySignature Sha256 for packageName=com.willblaschko.android.alexavoicelibrary
I/com.amazon.identity.auth.device.appid.APIKeyDecoder: verifyPayload for packageName=com.willblaschko.android.alexavoicelibrary
D/com.amazon.identity.auth.device.appid.APIKeyDecoder.PII: Signature checking.:<obscured>
I/com.amazon.identity.auth.device.appid.APIKeyDecoder: num sigs = 1
D/com.amazon.identity.auth.device.appid.APIKeyDecoder.PII: Fingerprint checking:<obscured>
I/com.amazon.identity.auth.device.appid.APIKeyDecoder:  num sigs = 1
D/com.amazon.identity.auth.device.appid.APIKeyDecoder.PII: Fingerpirints checking:<obscured>
W/com.amazon.identity.auth.device.appid.APIKeyDecoder: Failed to decode: Decoding fails: certificate fingerprint can't be verified! pkg=com.willblaschko.android.alexavoicelibrary
W/com.amazon.identity.auth.device.appid.APIKeyDecoder: Unable to decode APIKEy for pkg=com.willblaschko.android.alexavoicelibrary
E/AuthorizationHandler: Unable to Use Amazon Authorization Manager. APIKey is incorrect or does not exist. Does assets/api_key.txt exist in the main application?
                                                                                                java.lang.IllegalArgumentException: Invalid API Key
                                                                                                    at com.amazon.identity.auth.device.authorization.api.AmazonAuthorizationManager.<init>(AmazonAuthorizationManager.java:133)
                                                                                                    
```

in the app's build.gradle, I have

```
android {
...
signingConfigs {
        release {
            storeFile rootProject.file('debug.jks')
            keyAlias 'test'
            keyPassword 'test'
            storePassword 'test'
        }
    }

        buildTypes {
            debug{
                versionNameSuffix " Debug"
                minifyEnabled false
                shrinkResources true
                proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
                signingConfig signingConfigs.release
            }
            release {
                minifyEnabled false
                shrinkResources true
                proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
                signingConfig signingConfigs.release
            }
        }
...
}
```
Do you have an idea, what I may have screwed up? :)

Many thanks in advance,
Martin

**Comment by willblaschko** [comment]
Hi Martin,

Have you placed the ([security profile](https://developer.amazon.com/public/apis/engage/login-with-amazon/docs/register_security_profile.html)) api_key.txt file in your assets directory (app/src/main/assets)?

Also, I found the easiest way to get the key (in order to check if the key you used to create your security profile matches) is to push a signed app to the device with [this code](https://gist.github.com/willblaschko/95136b6b9e8b509213d616e5e09deeba).

So those are the first two I would check-- 1) whether you have placed api_key.txt (created when you create a security profile) in the proper location and 2) that your key matches. I'm guessing it's the former issue, as I've gotten that error as well when I forgot to add the file.

One other thing you might try, after, is changing the package name, I don't know how Amazon manages their security and signing, but you might need to create your own package namespace.

Let me know if this doesn't solve your issue.

**Comment by xtools-at** [comment]
Thanks for the blazing fast reply :)
api_key is in place and the right one, package name shouldn't be the issue too, I first missspelled it in the Dev Console (...alexa instead of ...alexavoicelibrary) and got an corresponding error which dissappeared after correcting it.

So you don't think my build.gradle is wrong? How do you manage the signing of the builds?

Going to try suggestion 2 and report back soon!

**Comment by willblaschko** [comment]
This is how I create my signing config: https://gist.github.com/willblaschko/8b108e1208dbe52eca69693c393d6e22

With real values substituted of course.This way I can make sure that both my release and debug have the same package name and signing keys (although you can change this as necessary).

**Comment by xtools-at** [comment]
thanks, that doesn't differ too much from mine :)
Nr. 2 did not work, so I renamed the package as you said and added it to the console - now it's up :+1: 
Sadly, the_ Login with Amazon_ or the Alexa service itself seems not to like my Austrian Amazon Account, I get an Error after Authorizing the App :( Too bad, would have liked to try Alexa out... Maybe I sign up as John Smith at amazon.com for testing purposes ;)

thanks for your help!!

**Comment by willblaschko** [comment]
It's an interesting platform, I think Amazon is going to roll out support to more places... "soon," but they don't discuss their development road map. I know a few other Europeans who have US accounts just to play around with it as well :).

Unless there's anything else, I'm going to close this issue.
