### ISSUE TITLE
android 4.4.2 not work

### ISSUE THREAD

**Issue by juntian018** [willblaschko/AlexaAndroid#30]
hi, I found that this code run on android4.4.2 had some problems, it would be error in handshake. log as below:
javax.net.ssl.SSLException: Connection closed by peer
08-24 15:20:43.661 11425-11786/com.willblaschko.android.alexavoicelibrary W/System.err:     at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
08-24 15:20:43.671 11425-11786/com.willblaschko.android.alexavoicelibrary W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:406)
08-24 15:20:43.806 11425-11786/com.willblaschko.android.alexavoicelibrary W/System.err:     at okhttp3.internal.io.RealConnection.connectTls(RealConnection.java:239)
08-24 15:20:44.171 11425-11786/com.willblaschko.android.alexavoicelibrary W/System.err:     at okhttp3.internal.io.RealConnection.establishProtocol(RealConnection.java:196)
08-24 15:20:44.246 11425-11786/com.willblaschko.android.alexavoicelibrary W/System.err:     at okhttp3.internal.io.RealConnection.buildConnection(RealConnection.java:171)
08-24 15:20:44.401 11425-11786/com.willblaschko.android.alexavoicelibrary W/System.err:     at okhttp3.internal.io.RealConnection.connect(RealConnection.java:111)
08-24 15:20:44.451 11425-11786/com.willblaschko.android.alexavoicelibrary W/System.err:     at okhttp3.internal.http.StreamAllocation.findConnection(StreamAllocation.java:187)
08-24 15:20:44.451 11425-11786/com.willblaschko.android.alexavoicelibrary W/System.err:     at okhttp3.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:123)
08-24 15:20:44.456 11425-11786/com.willblaschko.android.alexavoicelibrary W/System.err:     at okhttp3.internal.http.StreamAllocation.newStream(StreamAllocation.java:93)
08-24 15:20:44.456 11425-11786/com.willblaschko.android.alexavoicelibrary W/System.err:     at okhttp3.internal.http.HttpEngine.connect(HttpEngine.java:296)
08-24 15:20:44.466 11425-11786/com.willblaschko.android.alexavoicelibrary W/System.err:     at okhttp3.internal.http.HttpEngine.sendRequest(HttpEngine.java:248)
08-24 15:20:44.466 11425-11786/com.willblaschko.android.alexavoicelibrary W/System.err:     at okhttp3.RealCall.getResponse(RealCall.java:243)
08-24 15:20:44.471 11425-11786/com.willblaschko.android.alexavoicelibrary W/System.err:     at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:201)
08-24 15:20:44.471 11425-11786/com.willblaschko.android.alexavoicelibrary W/System.err:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:163)
08-24 15:20:44.481 11425-11786/com.willblaschko.android.alexavoicelibrary W/System.err:     at okhttp3.RealCall.execute(RealCall.java:57)
08-24 15:20:44.486 11425-11786/com.willblaschko.android.alexavoicelibrary W/System.err:     at com.willblaschko.android.alexa.interfaces.SendEvent.parseResponse(SendEvent.java:85)
08-24 15:20:44.486 11425-11786/com.willblaschko.android.alexavoicelibrary W/System.err:     at com.willblaschko.android.alexa.interfaces.SendEvent.completePost(SendEvent.java:75)
08-24 15:20:44.486 11425-11786/com.willblaschko.android.alexavoicelibrary W/System.err:     at com.willblaschko.android.alexa.interfaces.GenericSendEvent.<init>(GenericSendEvent.java:30)
08-24 15:20:44.501 11425-11786/com.willblaschko.android.alexavoicelibrary W/System.err:     at com.willblaschko.android.alexa.AlexaManager$9$1$1.doInBackground(AlexaManager.java:717)
08-24 15:20:44.541 11425-11786/com.willblaschko.android.alexavoicelibrary W/System.err:     at com.willblaschko.android.alexa.AlexaManager$9$1$1.doInBackground(AlexaManager.java:714)
08-24 15:20:44.596 11425-11786/com.willblaschko.android.alexavoicelibrary W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:288)
08-24 15:20:44.596 11425-11786/com.willblaschko.android.alexavoicelibrary W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
08-24 15:20:44.596 11425-11786/com.willblaschko.android.alexavoicelibrary W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
08-24 15:20:44.821 11425-11786/com.willblaschko.android.alexavoicelibrary W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
08-24 15:20:44.861 11425-11786/com.willblaschko.android.alexavoicelibrary W/System.err:     at java.lang.Thread.run(Thread.java:841)

**Comment by willblaschko** [comment]
This is a limitation of Amazon requiring TLS 1.2 (a byproduct of using HTTP/2), older devices don't support the new security protocol and I haven't found a workaround yet. Let me know if you find anything in your research.
