### ISSUE TITLE
No response after 2-3 tries, need to exit the app to recover.

### ISSUE THREAD

**Issue by amitks2015** [willblaschko/AlexaAndroid#31]
**I am using Nexus 5, Marshmallow. Downloaded the apk. I see it works good for 2-3 consecutive tries when I ask questions(Send Audio and not prerecorded). But after that I don't get any response. I see following exception in the log: What possibly is going wrong here?**

> 08-24 16:51:17.696 23814-24573/? W/System.err: java.io.IOException: stream was reset: CANCEL
08-24 16:51:17.696 23814-24573/? W/System.err:     at okhttp3.internal.framed.FramedStream.checkOutNotClosed(FramedStream.java:574)
08-24 16:51:17.696 23814-24573/? W/System.err:     at okhttp3.internal.framed.FramedStream.access$1200(FramedStream.java:34)
08-24 16:51:17.696 23814-24573/? W/System.err:     at okhttp3.internal.framed.FramedStream$FramedDataSink.emitDataFrame(FramedStream.java:508)
08-24 16:51:17.696 23814-24573/? W/System.err:     at okhttp3.internal.framed.FramedStream$FramedDataSink.write(FramedStream.java:488)
08-24 16:51:17.696 23814-24573/? W/System.err:     at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:176)
08-24 16:51:17.696 23814-24573/? W/System.err:     at okio.RealBufferedSink.write(RealBufferedSink.java:90)
08-24 16:51:17.699 23814-24573/? W/System.err:     at com.willblaschko.android.alexavoicelibrary.actions.SendAudioActionFragment$2.writeTo(SendAudioActionFragment.java:128)
08-24 16:51:17.699 23814-24573/? W/System.err:     at okhttp3.MultipartBody.writeOrCountBytes(MultipartBody.java:171)
08-24 16:51:17.699 23814-24573/? W/System.err:     at okhttp3.MultipartBody.writeTo(MultipartBody.java:113)
08-24 16:51:17.699 23814-24573/? W/System.err:     at okhttp3.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:704)
08-24 16:51:17.699 23814-24573/? W/System.err:     at okhttp3.internal.http.HttpEngine.readResponse(HttpEngine.java:563)
08-24 16:51:17.699 23814-24573/? W/System.err:     at okhttp3.RealCall.getResponse(RealCall.java:241)
08-24 16:51:17.704 23814-24573/? W/System.err:     at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:198)
08-24 16:51:17.704 23814-24573/? W/System.err:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:160)
08-24 16:51:17.705 23814-24573/? W/System.err:     at okhttp3.RealCall.execute(RealCall.java:57)
08-24 16:51:17.705 23814-24573/? W/System.err:     at com.willblaschko.android.alexa.interfaces.SendEvent.parseResponse(SendEvent.java:84)
08-24 16:51:17.705 23814-24573/? W/System.err:     at com.willblaschko.android.alexa.interfaces.SendEvent.completePost(SendEvent.java:74)
08-24 16:51:17.705 23814-24573/? W/System.err:     at com.willblaschko.android.alexa.interfaces.speechrecognizer.SpeechSendAudio.sendAudio(SpeechSendAudio.java:50)
08-24 16:51:17.707 23814-24573/? W/System.err:     at com.willblaschko.android.alexa.AlexaManager$9$1$1.doInBackground(AlexaManager.java:623)
08-24 16:51:17.707 23814-24573/? W/System.err:     at com.willblaschko.android.alexa.AlexaManager$9$1$1.doInBackground(AlexaManager.java:619)
08-24 16:51:17.707 23814-24573/? W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:295)
08-24 16:51:17.707 23814-24573/? W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
08-24 16:51:17.707 23814-24573/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
08-24 16:51:17.707 23814-24573/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
08-24 16:51:17.707 23814-24573/? W/System.err:     at java.lang.Thread.run(Thread.java:818)
08-24 16:51:17.707 23814-24573/? I/BaseActivity: Voice Error
08-24 16:51:17.707 23814-24573/? I/BaseActivity: Voice Complete
08-24 16:51:17.724 23814-23814/? I/BaseActivity: Total request time: 11026 miliseconds

**I used AlexaAndroid library with my app, and I see similar issue. Exactly after 2 tries I get error while sending event due to below error. What am I missing here? Any help really appreciated.**

08-24 16:39:02.714 22539-22699/? W/System.err: java.net.SocketTimeoutException: timeout
08-24 16:39:02.715 22539-22699/? W/System.err:     at okhttp3.internal.framed.FramedStream$StreamTimeout.newTimeoutException(FramedStream.java:600)
08-24 16:39:02.715 22539-22699/? W/System.err:     at okhttp3.internal.framed.FramedStream$StreamTimeout.exitAndThrowIfTimedOut(FramedStream.java:608)
08-24 16:39:02.715 22539-22699/? W/System.err:     at okhttp3.internal.framed.FramedStream$FramedDataSource.waitUntilReadable(FramedStream.java:379)
08-24 16:39:02.715 22539-22699/? W/System.err:     at okhttp3.internal.framed.FramedStream$FramedDataSource.read(FramedStream.java:342)
08-24 16:39:02.716 22539-22699/? W/System.err:     at okio.ForwardingSource.read(ForwardingSource.java:35)
08-24 16:39:02.716 22539-22699/? W/System.err:     at okio.RealBufferedSource$1.read(RealBufferedSource.java:409)
08-24 16:39:02.716 22539-22699/? W/System.err:     at java.io.InputStream.read(InputStream.java:162)
08-24 16:39:02.716 22539-22699/? W/System.err:     at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1025)
08-24 16:39:02.716 22539-22699/? W/System.err:     at org.apache.commons.io.IOUtils.copy(IOUtils.java:999)
08-24 16:39:02.716 22539-22699/? W/System.err:     at org.apache.commons.io.IOUtils.toByteArray(IOUtils.java:218)
08-24 16:39:02.717 22539-22699/? W/System.err:     at com.knowles.alexalibrary.interfaces.response.ResponseParser.parseResponse(ResponseParser.java:70)
08-24 16:39:02.717 22539-22699/? W/System.err:     at com.knowles.alexalibrary.interfaces.SendEvent.parseResponse(SendEvent.java:100)
08-24 16:39:02.717 22539-22699/? W/System.err:     at com.knowles.alexalibrary.interfaces.SendEvent.completePost(SendEvent.java:75)
08-24 16:39:02.717 22539-22699/? W/System.err:     at com.knowles.alexalibrary.interfaces.speechrecognizer.SpeechSendAudio.sendAudio(SpeechSendAudio.java:50)
08-24 16:39:02.717 22539-22699/? W/System.err:     at com.knowles.alexalibrary.AlexaManager$8$1$1.doInBackground(AlexaManager.java:578)
08-24 16:39:02.717 22539-22699/? W/System.err:     at com.knowles.alexalibrary.AlexaManager$8$1$1.doInBackground(AlexaManager.java:574)
08-24 16:39:02.718 22539-22699/? W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:295)
08-24 16:39:02.718 22539-22699/? W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
08-24 16:39:02.718 22539-22699/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
08-24 16:39:02.718 22539-22699/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
08-24 16:39:02.718 22539-22699/? W/System.err:     at java.lang.Thread.run(Thread.java:818)

**Comment by amitks2015** [comment]
Seems a network issue cause by poor wifi connection. Working elsewhere. Closing it.

**Comment by wgbuaa** [comment]
---java.net.SocketTimeoutException: timeout okhttp3.internal.framed.FramedStream$StreamTimeout.newTimeoutException(600)
okhttp3.internal.framed.FramedStream$StreamTimeout.exitAndThrowIfTimedOut(608)
okhttp3.internal.framed.FramedStream.getResponseHeaders(142)
okhttp3.internal.http.Http2xStream.readResponseHeaders(145)
okhttp3.internal.http.CallServerInterceptor.intercept(53)
okhttp3.internal.http.RealInterceptorChain.proceed(92)
okhttp3.internal.connection.ConnectInterceptor.intercept(45)
okhttp3.internal.http.RealInterceptorChain.proceed(92)
okhttp3.internal.http.RealInterceptorChain.proceed(67)
okhttp3.internal.cache.CacheInterceptor.intercept(109)
okhttp3.internal.http.RealInterceptorChain.proceed(92)
okhttp3.internal.http.RealInterceptorChain.proceed(67)
okhttp3.internal.http.BridgeInterceptor.intercept(93)
okhttp3.internal.http.RealInterceptorChain.proceed(92)
okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(124)
okhttp3.internal.http.RealInterceptorChain.proceed(92)
okhttp3.internal.http.RealInterceptorChain.proceed(67)
okhttp3.RealCall.getResponseWithInterceptorChain(170)
okhttp3.RealCall.execute(60)
com.android.volley.toolbox.w.a(102)
com.android.volley.toolbox.a.a(195)
com.android.volley.s.run(118)


I have the same problem and recover by restart my app.
especially using HTTP/2 protocol.  The okhttp version is 3.4.1.

**Comment by orafaaraujo** [comment]
Some problem here!
Internet network is good...
