### ISSUE TITLE
OpenDownchannel  response code : 200  response.body().contentLength() = -1? I run the simple app, when i send prerecorded audio, the responses is negative.

### ISSUE THREAD

**Issue by cloudlcw** [willblaschko/AlexaAndroid#36]
I'm not good at developing android application. But I have to make a app have access to AVS. I really can't  work it out.

**Comment by cloudlcw** [comment]
Would any one provide the source code of running app have access to AVS.

**Comment by willblaschko** [comment]
@cloudlcw the repo is a working application, see the compiled app [here](https://play.google.com/store/apps/details?id=com.willblaschko.android.alexavoicelibrary). 

Start by going through the code here and let me know if you have any specific questions.
