### ISSUE TITLE
Update speechutils to v0.2.04 to fix crash on Android v7.0

### ISSUE THREAD

**Issue by Kaljurand** [willblaschko/AlexaAndroid#38]
Consider updating speechutils to v0.2.04 (https://github.com/Kaljurand/speechutils/releases/tag/v0.2.04), which (hopefully) fixes a crash on Android v7.0 (discussed here https://github.com/Kaljurand/speechutils/issues/4).

**Comment by willblaschko** [comment]
Thanks for the update! Working on integrating this now :)
