### ISSUE TITLE
Request for example of signing.gradle configuration.

### ISSUE THREAD

**Issue by skypiri** [willblaschko/AlexaAndroid#44]
I cloned these code and opened source code with Android studio.
There is a error message like "Unable to find signing.gradle, please replace Android buildTypes > signing configs with your own configuration".
But I  need your help to resolve error. Could you show me a sample configuration for signing.gradle?

**Comment by skypiri** [comment]
I found your configuration from here. (https://gist.github.com/willblaschko/8b108e1208dbe52eca69693c393d6e22)
But I think it's better to include sample siging.gradle for your project.

**Comment by willblaschko** [comment]
The reason I don't include one is that Amazon requires each application to register on the dashboard with the application md5 hash. To encourage proper implementation and discourage abuse (and possible suspension of my developer account), I don't post my signing configuration.

Glad you got it figured out!

**Comment by meriki** [comment]
Hi @skypiri could you please elaborate on this? I'm new to Android. Do I have to just replace the buildtypes code with the siging.gradle?
