### ISSUE TITLE
authorization failed issue

### ISSUE THREAD

**Issue by a21052** [willblaschko/AlexaAndroid#45]
![c6903ab6-4a9e-11e6-9c65-0a5a1b1f048e](https://cloud.githubusercontent.com/assets/23086486/19745697/6e8e968c-9b98-11e6-9123-7faedc2cd1ab.png)

Tnx for the code and I am trying to compile and test the app. But I am getting an error right after I press I agree.

**Comment by skypiri** [comment]
I have same problem. If you resolve this issue, plz let me know...

**Comment by willblaschko** [comment]
Do you have Amazon.com accounts or are they Amazon.co.uk?

Also, at what stage of authentication are you seeing this issue?

**Comment by a21052** [comment]
Looks like some problem with the device configuration on my Amazon Developer account. 
Once I created a new device from a fresh account. The problem is solved.
