### ISSUE TITLE
Question regarding a time when start application.

### ISSUE THREAD

**Issue by skypiri** [willblaschko/AlexaAndroid#48]
When I start your application, it takes about 10 seconds to start to run. 
It takes always about 10 seconds to start application.
What happen to application to run? How can I reduce initial time to run?

11-02 16:54:56.640 27178-27178/? I/InstantRun: Instant Run Runtime started. Android package is com.willblaschko.android.alexavoicelibrary, real application class is com.willblaschko.android.alexavoicelibrary.AlexaApplication.
11-02 16:55:06.040 27178-27178/com.willblaschko.android.alexavoicelibrary I/AlexaApplication: <_FingerPrint_>

**Comment by abhijagtap73** [comment]
I also had same issue, this is because android studio instant run, you can uncheck instant run from android studio and run application, I hope it will work.

**Comment by willblaschko** [comment]
I reduced some of the clutter that slowed down the launch, hopefully it doesn't break any compatibility.
