### ISSUE TITLE
Could not log in to Amazon inside the Sample App.

### ISSUE THREAD

**Issue by stephencclau** [willblaschko/AlexaAndroid#49]
Hi,

I find that I could not log in to Amazon in the sample app by my Amazon developer account.
Do you know what amazon account is needed?
![screenshot_20161102-181329](https://cloud.githubusercontent.com/assets/13028321/19924743/34f7e4c4-a128-11e6-9c57-9f3c6a032da9.png)
![screenshot_20161102-181828](https://cloud.githubusercontent.com/assets/13028321/19924964/0ed58048-a129-11e6-95cf-379b5f15f40c.png)
Thank you very much.

**Comment by skypiri** [comment]
Did you input your id and password correctly? I've seen the same result before, but I resolve that issue after re-check my account information.

**Comment by stephencclau** [comment]
Hi,

Thank you very much for your prompt reply. 
I was dead loop inside these 2 login pages. And i have reset my password, and confirmed that they are correct by logged in by pc web browser.

I really want to try this app. Any suggestion to me?

Thank you very much. 

Best Regards'
Stephen Lau

**Comment by skypiri** [comment]
@stephencclau Do you have an account for Amazon.com or Amazon.co.uk?

**Comment by stephencclau** [comment]
Hi skypiri,

Thanks for your reply.
I am located in Hong Kong, and I think my account is Amazon.com.

Thanks a lot.

Best Regards'
Stephen Lau

**Comment by skypiri** [comment]
@stephencclau  I'm not sure what is your problem. But I'll share my experience to resolve issue.
My check points are account information and registration your product into AVS secure profile.
If you reset your password. please confirm once again using "SampleLoginWithAmazonApp". You can download source code from here.(https://developer.amazon.com/public/apis/engage/login-with-amazon/docs/run_sample_app_android.html)

If you can login you'll see your account information. Then your account information is correct.

Then, check registration information about your product.
Is it same your PRODUCT_ID in your source code in global/Constant.java with device type id in your profile.

FYI, I have accounts in Amazon.com and Amazon.co.uk. Both account are working well.

**Comment by amitks2015** [comment]
Hi,

As per your first mail, you have used your developer login credentials.
Can you try logging in with a user account which we use for shopping on
amazing.com.

Thanks,
Amit

**Comment by stephencclau** [comment]
@skypiri Thanks for your reply. From this point, I am using the App downloaded and installed from Google Play. So I have not been successfully compiled the sources. Thank you very much for the provided link of the "Android Sample App", I would try it tomorrow. Thanks.

**Comment by stephencclau** [comment]
@amitks2015 Yes, I am using my personal Amazon Developer account to login. I would try to create another one for shopping to test again tomorrow. Thank you very much.

Best Regards'
Stephen Lau

**Comment by stephencclau** [comment]
@amitks2015 I have tried a new account with www.amazon.com, still failed. But when I go to www.amazon.co.uk, it showed me that I have no account for my email. Then, I create the same account for co.uk with the same email and password. Then, I try again with the Alexa app, I could log in after 5 - 10 minutes later.
Thanks for your suggestion to make me successful to test the Alexa Android test app.
Thank you very much.

Best Regards'
Stephen Lau

**Comment by amitks2015** [comment]
@stephencclau good to hear that :)

**Comment by stephencclau** [comment]
Hi,

I want to summerize my experience with the Amazon Account Login using the AlexaAndroidLibrary,

When I firstly get to run the app, the following page would appear,
![1](https://cloud.githubusercontent.com/assets/13028321/19997807/eb6d4c9a-a2a3-11e6-85d7-f0ce829b88ae.png)
Then, I press the "details" option in the picture, it would bring me to,
![2](https://cloud.githubusercontent.com/assets/13028321/19998451/d70ffec4-a2a7-11e6-8f55-30605a33a75a.png)
when I scroll to the bottom, it shows me that I am not signed in,
![3](https://cloud.githubusercontent.com/assets/13028321/19998486/fd0ba1dc-a2a7-11e6-973c-d9c258727a3b.png)
And when I press sign in, it would bring me to the sign-in page,
![4](https://cloud.githubusercontent.com/assets/13028321/19998564/7da8afc4-a2a8-11e6-911d-7f74d619b309.png)
Then, I sign in with my account, scroll down to check my account again, it showed I am signed in,
![5](https://cloud.githubusercontent.com/assets/13028321/19998596/a2763114-a2a8-11e6-931a-ca129fb89eb3.png)
Then, I press back button to the app and press the microphone, following would appear,
![6](https://cloud.githubusercontent.com/assets/13028321/19998635/e7947aee-a2a8-11e6-8929-ed46d0fbdbc3.png)
Press the "continue" option.

From now on, I could use the Alexa service.

Thanks for your attention.

Stephen Lau

**Comment by willblaschko** [comment]
Glad you figured it out!
