### ISSUE TITLE
LWA SDK update

### ISSUE THREAD

**Issue by syedtalha** [willblaschko/AlexaAndroid#52]
The LWA for Android library has since updated, with major changes. 

Lattest ZIP available [ here ](https://images-na.ssl-images-amazon.com/images/G/01/lwa/sdk/LoginWithAmazonSDKForAndroid._TTH_.zip)

**Comment by skypiri** [comment]
Thanks for your update. The new library version is "3.0.0" and the old version is "2.0.2".
Where can I find the release note or official announcement for update ?

**Comment by syedtalha** [comment]
@skypiri 
[Here](https://developer.amazon.com/sdk-download#sdk_notes-1105548206) is the relevant link. Contents pasted here for reference. 
Login With Amazon (3.0) - Nov 03, 2016
New Features
Introduced new set of APIs with reduced amount of integration effort
Support ‘interactive strategy’ to allow end user define whether to show, always show, or never show SignIn flow when calling the Authorize API
Support ‘grant type’ to allow end user define whether to request for authorization code or OAuth access token (default) when calling the Authorize API
Return user profile data (if requested) and OAuth access token (if requested) in result of the Authorize API call
Support calling regionalized endpoints in Europe and Japan
Support independent integration with Pay with Amazon SDK
Compatibility
Backwards compatible to version 2.x and 1.x

**Comment by willblaschko** [comment]
This should be updated.
