### ISSUE TITLE
SSLException:Connection closed by peer.SSL_do_handshake on Android4.4.2

### ISSUE THREAD

**Issue by chenyingpingmp** [willblaschko/AlexaAndroid#54]
sir:
    I run the source code on device Android4.4.2
    I got this SSLException in OpenDownchannel.java connect(){response = currentCall.execute();}. the whole stackview is in the end.
    I am already try the CustomSslSocketFactory.java on the Internet,key word is "setEnabledProtocols(TLSv1.2)" and also try NativeCrypto.setEnabledProtocols(sslNativePointer, "TLSv1.2");,the error also apperaed. someone help me?thank you.

12-20 11:15:48.418 E/NativeCrypto( 1726): SESTEP jni Unknown error SSL_ERROR_SYSCALL during handshake
12-20 11:15:48.428 W/System.err( 1726): javax.net.ssl.SSLException: Connection closed by peer
12-20 11:15:48.428 W/System.err( 1726):         at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
12-20 11:15:48.428 W/System.err( 1726):         at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:439)
12-20 11:15:48.428 W/System.err( 1726):         at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:241)
12-20 11:15:48.428 W/System.err( 1726):         at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:198)
12-20 11:15:48.438 W/System.err( 1726):         at okhttp3.internal.connection.RealConnection.buildConnection(RealConnection.java:174)
12-20 11:15:48.438 W/System.err( 1726):         at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:114)
12-20 11:15:48.438 W/System.err( 1726):         at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:193)
12-20 11:15:48.438 W/System.err( 1726):         at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:129)
12-20 11:15:48.438 W/System.err( 1726):         at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:98)
12-20 11:15:48.438 W/System.err( 1726):         at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
12-20 11:15:48.438 W/System.err( 1726):         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
12-20 11:15:48.438 W/System.err( 1726):         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
12-20 11:15:48.438 W/System.err( 1726):         at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109)
12-20 11:15:48.448 W/System.err( 1726):         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
12-20 11:15:48.448 W/System.err( 1726):         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
12-20 11:15:48.458 W/System.err( 1726):         at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
12-20 11:15:48.458 W/System.err( 1726):         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
12-20 11:15:48.458 W/System.err( 1726):         at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)
12-20 11:15:48.458 W/System.err( 1726):         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
12-20 11:15:48.458 W/System.err( 1726):         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
12-20 11:15:48.458 W/System.err( 1726):         at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
12-20 11:15:48.458 W/System.err( 1726):         at okhttp3.RealCall.execute(RealCall.java:60)
12-20 11:15:48.458 W/System.err( 1726):         at com.willblaschko.android.alexa.interfaces.system.OpenDownchannel.connect(OpenDownchannel.java:65)
12-20 11:15:48.458 W/System.err( 1726):         at com.willblaschko.android.alexa.AlexaManager$5$1$1.doInBackground(AlexaManager.java:222)
12-20 11:15:48.458 W/System.err( 1726):         at com.willblaschko.android.alexa.AlexaManager$5$1$1.doInBackground(AlexaManager.java:1)
12-20 11:15:48.458 W/System.err( 1726):         at android.os.AsyncTask$2.call(AsyncTask.java:288)
12-20 11:15:48.458 W/System.err( 1726):         at java.util.concurrent.FutureTask.run(FutureTask.java:237)
12-20 11:15:48.458 W/System.err( 1726):         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
12-20 11:15:48.458 W/System.err( 1726):         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
12-20 11:15:48.458 W/System.err( 1726):         at java.lang.Thread.run(Thread.java:841)
12-20 11:15:48.468 I/BaseActivity( 1726): Event Error
12-20 11:15:48.468 I/BaseActivity( 1726): Event Complete

**Comment by willblaschko** [comment]
#71 see this issue.
