### ISSUE TITLE
I can't find the apk in this app

### ISSUE THREAD

**Issue by MiniMelissa** [willblaschko/AlexaAndroid#55]
Hi all,

I download this sample app, when I use android studio2.1.3 to open it, it shows :
Error:(7, 0) Unable to find signing.gradle, please replace Android buildTypes > signing configs with your own configuration.
I think I need to add api_key.txt before run. 
But if I need to get the api_key.txt file ,I need to find the apk to get the SHA-256 or MD5 value to generate the api key on these 2 webpages https://sellercentral.amazon.com/ or https://developer.amazon.com/avs/home.html#/

Who can give me some advice?

Thank you!

**Comment by willblaschko** [comment]
@MiniMelissa set up the signing config first, because you need to have the MD5 value of the signed APK to get the API key.

If you want an easy way to get the MD5 hash once signed, use the SigningKey.getCertificateMD5Fingerprint() method in the library.
