### ISSUE TITLE
ResponseParser "PausePrompt" handling

### ISSUE THREAD

**Issue by raghavpai** [willblaschko/AlexaAndroid#56]
Hi Will,
As I can see in AlexaAudioPlayer, you have handled the "PausePrompt" by playing the mp3 from assets, but i guess we need to remove the following code from parser ResponseParser.
                    /*
                    * hacky workaround proposed by Eric@Amazon (https://forums.developer.amazon.com/questions/28021/response-about-the-shopping-list.html)
                    * to skip any items that are PausePrompts which don't play correctly on Android (malformed MP3s?)
                    */
                    if(!TextUtils.isEmpty(directive) && directive.toLowerCase().contains("PausePrompt")){
                        continue;
                    }

Best Regds
Raghav

**Comment by willblaschko** [comment]
Yes, it can be removed. Because of a bug in the code ("PausePrompt" will never match with a toLowerCase() String), it never got hit anyway, but it's extra code now.
