### ISSUE TITLE
Do I need to build the sample project with gradle 2.3.1-beta?

### ISSUE THREAD

**Issue by gfhyang** [willblaschko/AlexaAndroid#60]
Hi Sir,
I test the app download from Google Play store and it works well. 
You really do a great work!!!

I try to build the project clone from the github but I got error. My gradle of Android Studio is v2.2.2.
The build error says:
**Error:(1, 0) The android gradle plugin version 2.3.0-beta1 is too old, please update to the latest version.**
Do I need to upgrade my gradle to 2.3.0-beta1? Or I just change the gradle version to v2.2.2?

I have tried to build this project with gradle v2.2.2 then I encounter another problem about signing config
So I mark those part in the gradle then compiler it successfully.

Then I attach my own api_key.txt to assets folder. I test the apk I bulild on my phone then every time I press
the record button on the app, it will show my browser up for 2-3 secs then the browser will be close.

Why does the Browse show up then I could login with my accout?
Do I use the wrong api_key.txt?

About the PRODUCT_ID? Do I just change it to the name which I register on the 
Amazon Developer console?

Any Suggestion?
Thank you very much for your great help.

Best regards
Randy Yang

**Comment by amitks2015** [comment]
What's the error you are getting when browser closes automatically?

Are you using correct PRODUCT_ID? It's supposed to be "Application Type ID
" which you get at developer console after your app registration with Alexa.

Thanks,
Amit

**Comment by vkreal** [comment]
Hey, I fixed same issue`Error:(1, 0) The android gradle plugin version 2.3.0-beta1 is too old, please update to the latest version.` take a look at https://github.com/vkreal/AlexaAndroid

**Comment by gfhyang** [comment]
I saw the error from my Android Monitor

**AuthError cat= INTERNAL type=ERROR_SERVER_REPSONSE - com.amazon.identity.auth.device.AuthError: Error=invalid_scope error_description=An unknown scope was requested**

com.amazon.identity.auth.device.authorization.AuthorizationActivity: Receiving response for auth request
com.amazon.identity.auth.device.RequestManager.PII: Handling response for request 7af59f34-9fdf-482c-8c0b-91223ed0f5ae:<obscured>
com.amazon.identity.auth.device.authorization.AuthorizationResponseProcessor.PII: Received response from WebBroswer for OAuth2 flow:<obscured>
com.amazon.identity.auth.device.authorization.AuthorizationResponseParser.PII: Received response from WebBroswer for OAuth2 flow:<obscured>
com.amazon.identity.auth.device.authorization.AuthorizationResponseParser.PII: Code extracted from response:<obscured>
System.err: AuthError cat= INTERNAL type=ERROR_SERVER_REPSONSE - com.amazon.identity.auth.device.AuthError: Error=invalid_scope error_description=An unknown scope was requested
System.err:     at com.amazon.identity.auth.device.authorization.AuthorizationResponseParser.constructErrorBundle(AuthorizationResponseParser.java:82)
System.err:     at com.amazon.identity.auth.device.authorization.AuthorizationResponseParser.extractResultsBundle(AuthorizationResponseParser.java:54)
System.err:     at com.amazon.identity.auth.device.authorization.AuthorizationResponseProcessor.handleResponse(AuthorizationResponseProcessor.java:24)
System.err:     at com.amazon.identity.auth.device.authorization.AuthorizationRequest.handleResponse(AuthorizationRequest.java:44)
System.err:     at com.amazon.identity.auth.device.RequestManager.handleResponse(RequestManager.java:81)
System.err:     at com.amazon.identity.auth.device.RequestManager.handleResponse(RequestManager.java:69)
System.err:     at com.amazon.identity.auth.device.workflow.WorkflowActivity.handleResponseUri(WorkflowActivity.java:52)
System.err:     at com.amazon.identity.auth.device.authorization.AuthorizationActivity.onCreate(AuthorizationActivity.java:23)
System.err:     at android.app.Activity.performCreate(Activity.java:6248)
System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1125)
System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2437)
System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2544)
System.err:     at android.app.ActivityThread.access$900(ActivityThread.java:150)
System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1394)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
System.err:     at android.os.Looper.loop(Looper.java:168)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:5845)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)
BaseActivity: Event Error
com.amazon.identity.auth.device.authorization.AuthorizationActivity: finish

**Comment by gfhyang** [comment]
Thank you for prompt reply @amitks2015 , it really helps to me, after I fill in the correct PRODUCT_ID and attached the api_key.txt which retrieved from the security profile, I could successfully run the sample app on my android phone.

**Comment by pavansingoji** [comment]
Is App ID and PRODUCT_ID are same in Amazon Alexa development console ?
Please help me.
Thanks in Advance
