### ISSUE TITLE
How do i integrate my Skill in your sample application

### ISSUE THREAD

**Issue by junaidwarsi1994** [willblaschko/AlexaAndroid#66]
i was able to  run your sample application and its just simply great but my questions is how do i integrate my skill with few changes in your code ?

**Comment by ihavenoface5** [comment]
Skills are not exactly the usage case for this library. If you want to implement your skill with Alexa, see https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/getting-started-guide
