### ISSUE TITLE
com.amazon.identity.auth.device.api.InvalidIntegrationException: WorkflowActivity is not declared in your app's AndroidManifest.xml Enable manifest merging or refer to the integration guide to manually add WorkflowActivity to your manifest.

### ISSUE THREAD

**Issue by jorgesilva** [willblaschko/AlexaAndroid#68]
When attempting to integrate the library into my own app, it seems that the library (2.4.2) is expecting me to have a declaration for an activity named WorkflowActivity, but the activity does not exist in the library... was it renamed perhaps?

**Comment by willblaschko** [comment]
It looks like it's an Activity in the Login With Amazon library, probably one of the ones required to authenticate your user. 

Make sure you're properly merging your manifests to include all the resources from all libraries:
https://developer.android.com/studio/build/manifest-merge.html

**Comment by jorgesilva** [comment]
ok, it is sorted out. I think this is the result of two omissions in the documentation:

1. The Login with Amazon library seems to already be included in this library
2. People integrating the library still have to go through the integration steps outlined at: https://developer.amazon.com/public/apis/engage/login-with-amazon/docs/create_android_project.html

Incidentally, this page also explains how to add the api key to the project, so it might be a good idea to add it to the documentation.
