### ISSUE TITLE
Getting auth issue form Amazon

### ISSUE THREAD

**Issue by TheOrangeTester** [willblaschko/AlexaAndroid#7]
Hi Guys,

I am getting following issue from amazon after asking for permission,
 
![screenshot_2016-05-30-10-38-22 1](https://cloud.githubusercontent.com/assets/13374320/15646371/e1b3b748-267a-11e6-97a4-4dbc50c77dbe.png)

I have entered Product_ID,api_key correctly

This is kind request to help me to resolve this issue .

**Comment by willblaschko** [comment]
#6 duplicate issue

**Comment by rahuljeyaraj** [comment]
Hi TheOrangeTester,

I was also facing the same issue.

Registration of application and creation of security profile should be done using the Amazon US account only. Then you will not see the above mentioned issue.

Cheers
Rahul

**Comment by TheOrangeTester** [comment]
Hi rahuljeyaraj,

Thanks for your help!!!!
How to create Amazon US account ?
Does this means we just need to register with US address ?
Again Thanks in advance!

**Comment by vw2k3** [comment]
@rahuljeyaraj 
Thank tou for the help!
Can U tell us how to create an Amazon US account if not in US?

**Comment by TheOrangeTester** [comment]
@vw2k3 you just need to register account with US address.

**Comment by vw2k3** [comment]
Hi @TheOrangeTester 
You solve the issue just after modify the address to US address?!
I create a new Amazon account, and go to "Manage Addresses and 1-Click Settings" to add an US address. But still face the error... Should I set address in other place?
Thank you for the reply!

**Comment by TheOrangeTester** [comment]
Hi @vw2k3 ,
I have created account with new email address. 
I have no idea about above method will work or not.

**Comment by quangson8128** [comment]
Hi everyone,
I just try to run demo but I still have some problem when authenticate.
For setting demo, I see variable "PRODUCT_ID" in constants class.
So what is value should I put there.
Please help me what's PRODUCT_ID in amazone developer page.

Thanks.

**Comment by quangson8128** [comment]
I also check:

https://developer.amazon.com/public/solutions/alexa/alexa-voice-service/docs/authorizing-your-alexa-enabled-mobile-app

In this page I see some snip code:

private String PRODUCT_ID = INSERT YOUR PRODUCT ID FROM Amazon developer portal

So
"YOUR PRODUCT ID FROM Amazon developer portal" -> What's it ?

**Comment by joinee0208** [comment]
I have the same problem.as follows:

@TheOrangeTester I have created account with new email address with US address in step4. but the error is still existed.

by the way,there are two type accounts:
1 the avs device developer account.
2 the normal consumers‘s account.  
two type account all need to be US address?

hope someone can help me? thanks.


step1:
![step1](https://cloud.githubusercontent.com/assets/3191056/16030229/da048592-3221-11e6-88ee-6eb37ba4d4b6.png)

step2:
![step2](https://cloud.githubusercontent.com/assets/3191056/16030231/dd8b821a-3221-11e6-8495-bb1875e04f23.png)

step3:
![step3](https://cloud.githubusercontent.com/assets/3191056/16030235/e10c122e-3221-11e6-8443-75954dc8b67a.png)

step4:
![step4](https://cloud.githubusercontent.com/assets/3191056/16030236/e3c42a88-3221-11e6-8332-f57a703e34bb.png)

step5:
![step5](https://cloud.githubusercontent.com/assets/3191056/16030238/e73f8d56-3221-11e6-896b-cca4b4468bb9.png)

step6:
![step6](https://cloud.githubusercontent.com/assets/3191056/16030241/eb9e925c-3221-11e6-9a5f-98c6d2e48bf6.png)

**Comment by mattgmg1990** [comment]
I think you might have already mentioned this, but I struggled for most of the day with the same error message and for me it was because I did not change [PRODUCT_ID](https://github.com/willblaschko/AlexaAndroid/blob/master/app/src/main/java/com/willblaschko/android/alexavoicelibrary/global/Constants.java#L8) to the value for my Alexa application that you configure for "Application Type Id."

After I changed that to make my application id, everything worked.

**Comment by willblaschko** [comment]
I've added your pull request to the README, @mattgmg1990 , thanks for the update.

**Comment by mattgmg1990** [comment]
Awesome! I hope that resolves the issues for @joinee0208 and @TheOrangeTester but there could be other issues at play here.
