### ISSUE TITLE
Davlik warnings and errors running on 4.4.2

### ISSUE THREAD

**Issue by jonruiz** [willblaschko/AlexaAndroid#71]
First off, thanks for making this code available! I can compile and run it fine on 5.0
[Output.txt](https://github.com/willblaschko/AlexaAndroid/files/883597/Output.txt)
. From the minimum SDK and code, it looks like it should work fine on 4.4.2, but when I try to run it and use "send text", I get a bunch of davlik warnings and errors and tAny idea what's going wrong?nt. It looks like it can't even open an SSL connection. Any idea what's going wrong?

[Output.txt](https://github.com/willblaschko/AlexaAndroid/files/883598/Output.txt)

Any help is greatly appreciated!

Thanks,
Jon

**Comment by willblaschko** [comment]
OkHttp doesn't support the required connection to the newest Alexa endpoint on versions lower than X (5.0 I think). Something about the way HTTP/2 connections are made and the security certs required to connect not being available on older devices.
