### ISSUE TITLE
Is there a detailed user guide to how use your app

### ISSUE THREAD

**Issue by khalil-rashow** [willblaschko/AlexaAndroid#76]
Hi,

Is there a step by step guide to how to use your sample app as am new to such apps. I have already used companion sample app of alexa and tested my my skills over raspberry and android and now I would like to use an app which authenticate itself and interacts with alexa such as your app. 
I read readme of your project and I tried to open it by android studio but I encountered with an error saying that "unable to find signing.gradle file".

Thanks in advance.

**Comment by willblaschko** [comment]
If you want to try a working version of this, you can use the full-featured one:
https://play.google.com/store/apps/details?id=com.willblaschko.android.alexalistens&hl=en

Or the one directly based on this repo:
https://play.google.com/store/apps/details?id=com.willblaschko.android.alexavoicelibrary&hl=en

**Comment by javaand** [comment]
Thank you so much @willblaschko ,
I already installed these two apps(Apk) but what I would like is installing the code and test it in my pc to be familiar with such app. I already installed and run companion app and I would like the same thing if is possible.

Thanks in adavnce

**Comment by khalil-rashow** [comment]
Finally I installed and runned it successfully. Thank you much
