### ISSUE TITLE
Not able to invoke custom skill

### ISSUE THREAD

**Issue by philneus** [willblaschko/AlexaAndroid#77]
Hi,
I was able to install your app as a signed apk file. The security rofile has the same signature as the app and I copied the Key to the apk_key.txt file.

I implemented a custom skill [here](https://developer.amazon.com/edw/home.html#/skills) and enabled the skill for my account . A test with https://echosim.io/ was succesful using the instruction "Alexa, start MySkill". This does not work with your App; Alexa only responds that the skill does not exist. Any Idea how to fix this? Are custom skills possible on Android?

Public skills like the Ted Talk skill are handled without any problems by your App.

**Comment by khalil-rashow** [comment]
@philneus please could you explain how you installed the app. (If it is possible step by step)

thanks in advance.

**Comment by ihavenoface5** [comment]
Custom skills are possible. Download the Amazon Alexa app and see what she thought you said in the settings/history section. I found this was an easy way to debug what was going on.

**Comment by willblaschko** [comment]
@ihavenoface5 this is a great way to do it. Or here if you want to use the browser: http://alexa.amazon.com/spa/index.html#settings/dialogs

The big thing is make sure you're logged into the same account for both.
