### ISSUE TITLE
Detecting end of voice recording

### ISSUE THREAD

**Issue by jmckinley** [willblaschko/AlexaAndroid#8]
I have had no success in having the app stop a recording event automatically when I am done speaking.  I have to manually stop recording by hitting the microphone button again.

**Comment by willblaschko** [comment]
Is this on the sample app? I've had issues with high-noise environments, but generally in quieter areas it works fine.

None of the functions in the library do auto end of speech detection, that all has to be handled on the app side.

**Comment by jmckinley** [comment]
It was with the sample app. It was not a very high noose environment, in
this case. I was thinking there was logic for end of speech detection,
given the text displayed on the input screen of the sample app.  Am I wrong?

On Thursday, June 2, 2016, Will Blaschko <notifications@github.com> wrote:

> Is this on the sample app? I've had issues with high-noise environments,
> but generally in quieter areas it works fine.
>
> None of the functions in the library do auto end of speech detection, that
> all has to be handled on the app side.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/willblaschko/AlexaAndroid/issues/8#issuecomment-223413649>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAEN_QEZGEhay5vvF4eFeRcoYJRXKXY2ks5qHz5OgaJpZM4IsyNj>
> .
>


-- 
www.lert.ly
Bringing the Internet Of Things To Personal Safety Solutions

**Comment by willblaschko** [comment]
The sample app is supposed to support it, but the library I'm using for the feature isn't perfect. It works on some devices (my nVidiaShield TV) much better than others (my Nexus 5X). I've been doing research into better end of speech detection, but it hasn't been top priority.

**Comment by jmckinley** [comment]
Thanks

On Thursday, June 2, 2016, Will Blaschko <notifications@github.com> wrote:

> The sample app is supposed to support it, but the library I'm using for
> the feature isn't perfect. It works on some devices (my nVidiaShield TV)
> much better than others (my Nexus 5X). I've been doing research into better
> end of speech detection, but it hasn't been top priority.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/willblaschko/AlexaAndroid/issues/8#issuecomment-223430824>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAEN_XGSM4HneKgCrljzqsgt-l6-ndTtks5qH01-gaJpZM4IsyNj>
> .
>


-- 
www.lert.ly
Bringing the Internet Of Things To Personal Safety Solutions

**Comment by rowol** [comment]
Will, I'm curious, why are you using the library to detect when you should end the capture, rather than processing the Stop Capture message from your AVS Down Channel service?   I wasn't getting the end of capture working the way I wanted with the speechutils library, so I set up the service and was considering processing Alexa's stop capture instead... is that a bad idea for some reason?
