### ISSUE TITLE
Could we invoke the app with "alexa" wake word without pressing the button?

### ISSUE THREAD

**Issue by khalil-rashow** [willblaschko/AlexaAndroid#81]
Hi everyone,

Could we invoke alexa through this app by invoking word "Alexa" without pressing the button? like Amazon Dot

Thanks in advance.

**Comment by willblaschko** [comment]
The app I made that uses this library does: https://play.google.com/store/apps/details?id=com.willblaschko.android.alexalistens&hl=en

However, I wanted to make the library available for people to use as they please for whatever application and not lock them into certain features.

**Comment by ruscles** [comment]
Hi,

I am also interested in this functionality. Do you have any example code for how to listen for specific words?

**Comment by willblaschko** [comment]
I am using this library for my implementation, it's pretty easy to just drop in and attach to a background service: https://github.com/cmusphinx/pocketsphinx

It's not the most accurate solution, but by tweaking the options it's decent.

**Comment by ruscles** [comment]
Could you provide any pointers as to how you implemented this? I am able to get pocketsphinx to recognize the word "Alexa," but then it does not play nice with the AlexaLibrary trying to use the microphone to record the actual question. I call startlistening from onResult when pocketsphinx stops listening:
```
@Override
    public void onResult(Hypothesis hypothesis) {
        if (hypothesis.getHypstr().equals("alexa")) {
            startListening();
        }
    }
```
```
@Override
    public void startListening() {
        if (recorder == null) {
            recorder = new RawAudioRecorder(AUDIO_RATE);
        }
        recorder.start();
        mAlexaManager.sendAudioRequest(requestBody, getRequestCallback());
    }
```

But then creating the requestBody loops forever with 0 rmsdb:

```
I/SpeechTextFragment: Received audio
I/SpeechTextFragment: RMSDB: 0.0
```

The recorder works just fine when it starts from a button click. Any help would be appreciate, thanks!
