### ISSUE TITLE
Api support below Lollipop

### ISSUE THREAD

**Issue by nangsan** [willblaschko/AlexaAndroid#92]
Current library minSdkVersion is pointing Lollipop,
is there any specific reason for not supporting older version API.

**Comment by javaand** [comment]
Hi @nangsan 
Alexa exposes its endpoints over http/2 and it requires TLSv1.2 as a secure protocol. Android started supporting TLSv1.2 for 16+ versions without enabling it by default and it enabled it by default for 20+. and there is a problem when trying to enable for 16+. As a result Alexa works properly for 20+ and for this reason this sample app requires 21 as a minsdkversion.
Hope to help you.

**Comment by nangsan** [comment]
Hi @javaand 
Thanks for the info!
This library uses Okhttp3 for making http2 requests, and Okhttp supports from Android 2.3+ devices.
And Okhttp has been tracking this issue(supporting TLSv1.2 for <20+ versions) and somehow they find a solution for that and I'm referencing that issue([More info](https://github.com/square/okhttp/issues/2372)).

I don't know much about TLS, though I found this in Okhttp, hope it helps.

**Comment by willblaschko** [comment]
There's a combination issue here:
1) http2 support
2) TLSv1.2 support (and)
3) Security cert signing

See this:
https://forums.developer.amazon.com/questions/30084/enable-tls-11.html

There are a lot of devices that should support http2 and TLS v1.2 based on their Android version but don't, or that do but don't have the right AES encryption to be supported by Alexa.

It seemed safer (based on what I observed in my user base) to make the minimum 21+ versus 16+. There were lots of negative reviews from users <= 20. If your project will be working with a known subset of Android devices whose configuration you can control, you can set this level to whatever you need as long as all the libraries support it.

**Comment by nangsan** [comment]
Hi @willblaschko 
Thanks for the info, and I have another question.
Current Library Version(2.4.2) doesn't handle SetEndpoint Directive,
but the master branch has a solution for that
but doesn't deal with login check.
Is the master branch still in development?
Is it okay to port the master code as a library?
